version: '3'
services:
  oem-back:
      build: ./back
      container_name: oem-back
      ports:
        - 6000:6000
      volumes:
        - ../../gateways/oemmanuf:/config/gateways/importerorg
        - ../../wallets/oemmanuf:/config/wallets/importerorg
      tty: true

  oem-front:
      build: ./front
      container_name: oem-front
      ports:
        - 81:80
      links:
        - oem-back
      tty: true