version: '2'
services:
  oem-back:
      build: ./back
      container_name: oem-back
      ports:
        - 6000:6000
      volumes:
        - ../../gateways/oemmanuf:/config/gateways/oemmanuf
        - ../../wallets/oemmanuf:/config/wallets/oemmanuf
      tty: true

  oem-front:
      build: ./front
      container_name: oem-front
      ports:
        - 81:80
      depends_on:
        - oem-back
      tty: true
