// Generated by https://quicktype.io

export interface AvisoActualizacion {
    $schema:     string;
    $id:         string;
    title:       string;
    description: string;
    type:        string;
    properties:  AvisoActualizacionProperties;
}

export interface AvisoActualizacionProperties {
    id_documento:      DateClass;
    id_fab_vehic:      DateClass;
    systems_to_update: SystemsToUpdate;
    date:              DateClass;
}

export interface DateClass {
    description: string;
    type:        string;
}

export interface SystemsToUpdate {
    description: string;
    type:        string;
    items:       Items;
}

export interface Items {
    type:       string;
    properties: ItemsProperties;
}

export interface ItemsProperties {
    id_emb_sys:     DateClass;
    description:    DateClass;
    type_of_update: TypeOfUpdate;
}

export interface TypeOfUpdate {
    description: string;
    type:        string;
    values:      string[];
}
