// Generated by https://quicktype.io

export interface CertifVehic {
    $schema:     string;
    $id:         string;
    title:       string;
    description: string;
    type:        string;
    properties:  Properties;
}

export interface Properties {
    ref_doc_descripcion: Fecha;
    id_homologador:      Fecha;
    id_documento:        Fecha;
    fecha:               Fecha;
    firma:               Fecha;
}

export interface Fecha {
    description: string;
    type:        string;
}
