// Generated by https://quicktype.io

export interface DecisionTipoUpdate {
    $schema:     string;
    $id:         string;
    title:       string;
    description: string;
    type:        string;
    properties:  DecisionTipoUpdateProperties;
}

export interface DecisionTipoUpdateProperties {
    id_doc:                       Fecha;
    fecha:                        Fecha;
    id_oem_manuf:                 Fecha;
    update_type_decission:        UpdateTypeDecission;
    quality_controls:             QualityControls;
    changes_evaluation:           ChangesEvaluation;
    regulation_impact_evaluation: RegulationImpactEvaluation;
    modifications_on_system:      ModificationsOnSystem;
    changes_in_functionality:     ChangesInFunctionality;
}

export interface ChangesEvaluation {
    description: string;
    type:        string;
    items:       ChangesEvaluationItems;
}

export interface ChangesEvaluationItems {
    type:       string;
    properties: PurpleProperties;
}

export interface PurpleProperties {
    name_of_change: Fecha;
    description:    Fecha;
    observaciones:  Fecha;
}

export interface Fecha {
    description: string;
    type:        Type;
}

export enum Type {
    String = "string",
}

export interface ChangesInFunctionality {
    description: string;
    type:        string;
    items:       ChangesInFunctionalityItems;
}

export interface ChangesInFunctionalityItems {
    type:       string;
    properties: FluffyProperties;
}

export interface FluffyProperties {
    name_of_functionality: Fecha;
    description:           Fecha;
    change_applied:        UpdateTypeDecission;
}

export interface UpdateTypeDecission {
    description: string;
    type:        Type;
    values:      string[];
}

export interface ModificationsOnSystem {
    description: string;
    type:        string;
    items:       ModificationsOnSystemItems;
}

export interface ModificationsOnSystemItems {
    type:       string;
    properties: TentacledProperties;
}

export interface TentacledProperties {
    modification_name: Fecha;
    description:       Fecha;
}

export interface QualityControls {
    description: string;
    type:        string;
    items:       QualityControlsItems;
}

export interface QualityControlsItems {
    type:       string;
    properties: StickyProperties;
}

export interface StickyProperties {
    id_control:  Fecha;
    description: Fecha;
}

export interface RegulationImpactEvaluation {
    description: string;
    type:        string;
    items:       RegulationImpactEvaluationItems;
}

export interface RegulationImpactEvaluationItems {
    type:       string;
    properties: IndigoProperties;
}

export interface IndigoProperties {
    id_rule:     Fecha;
    impact:      Fecha;
    conclusions: Fecha;
}
