// Generated by https://quicktype.io

export interface DescripcionVehic {
    $schema:     string;
    $id:         string;
    title:       string;
    description: string;
    type:        string;
    properties:  DescripcionVehicProperties;
}

export interface DescripcionVehicProperties {
    id_doc:       IDDoc;
    codif_modelo: CodifModelo;
    sistemas:     Sistemas;
}

export interface CodifModelo {
    description: string;
    type:        string;
    properties:  CodifModeloProperties;
}

export interface CodifModeloProperties {
    marca:       IDDoc;
    modelo:      IDDoc;
    id_vehículo: IDDoc;
}

export interface IDDoc {
    description: string;
    type:        string;
}

export interface Sistemas {
    description: string;
    type:        string;
    items:       SistemasItems;
}

export interface SistemasItems {
    type:       string;
    properties: ItemsProperties;
}

export interface ItemsProperties {
    nombre:  IDDoc;
    manager: Manager;
}

export interface Manager {
    description: string;
    type:        string;
    properties:  ManagerProperties;
}

export interface ManagerProperties {
    identificador:        IDDoc;
    nombre:               IDDoc;
    sistemas_controlados: SistemasControlados;
}

export interface SistemasControlados {
    description: string;
    type:        string;
    items:       SistemasControladosItems;
}

export interface SistemasControladosItems {
    type: string;
}
