// Generated by https://quicktype.io

export interface DescripcionSysEmbbed {
    $schema:     string;
    $id:         string;
    title:       string;
    description: string;
    type:        string;
    properties:  DescripcionSysEmbbedProperties;
}

export interface DescripcionSysEmbbedProperties {
    id:        Fecha;
    nombre:    Fecha;
    fecha:     Fecha;
    id_fabric: Fecha;
    version:   Fecha;
    hw_elem:   WElem;
    sw_elem:   WElem;
}

export interface Fecha {
    description: string;
    type:        Type;
}

export enum Type {
    String = "string",
}

export interface WElem {
    description: string;
    type:        string;
    items:       Items;
}

export interface Items {
    type:       string;
    properties: ItemsProperties;
}

export interface ItemsProperties {
    num_modelo:             Fecha;
    nombre_coloquial:       Fecha;
    version:                Fecha;
    fecha:                  Fecha;
    decission_document_id?: Fecha;
}
