// Generated by https://quicktype.io

export interface Justification {
    $schema:     string;
    $id:         string;
    title:       string;
    description: string;
    type:        string;
    properties:  Properties;
}

export interface Properties {
    id_documento:       DateClass;
    id_fab:             DateClass;
    id_doc_descripcion: DateClass;
    decission:          Decission;
    justification:      DateClass;
    date:               DateClass;
}

export interface DateClass {
    description: string;
    type:        string;
}

export interface Decission {
    description: string;
    type:        string;
    values:      string[];
}
