// Generated by https://quicktype.io

export interface Pruebas {
    $schema:     string;
    $id:         string;
    title:       string;
    description: string;
    type:        string;
    properties:  Properties;
}

export interface Properties {
    id_prueba:         PurpleDate;
    id_documento:      PurpleDate;
    id_oem_manuf:      PurpleDate;
    id_embbed_sys:     PurpleDate;
    sistemas_probados: SistemasProbados;
    tipo_de_prueba:    TipoDePrueba;
    description:       PurpleDate;
    expected_results:  PurpleDate;
    obtained_results:  PurpleDate;
    proof_validation:  PurpleDate;
    date:              PurpleDate;
}

export interface PurpleDate {
    description: string;
    type:        string;
}

export interface SistemasProbados {
    description: string;
    type:        string;
    items:       Items;
}

export interface Items {
    type: string;
}

export interface TipoDePrueba {
    description: string;
    type:        string;
    values:      string[];
}
