// Generated by https://quicktype.io

export interface VersionInfo {
    $schema:     string;
    $id:         string;
    title:       string;
    description: string;
    type:        string;
    properties:  VersionInfoProperties;
}

export interface VersionInfoProperties {
    id_documento:         Rxswin;
    version:              Rxswin;
    integrity_validation: Rxswin;
    RXSWIN:               Rxswin;
    updated_systems:      UpdatedSystems;
}

export interface Rxswin {
    description: string;
    type:        string;
}

export interface UpdatedSystems {
    description: string;
    type:        string;
    items:       Items;
}

export interface Items {
    type:       string;
    properties: ItemsProperties;
}

export interface ItemsProperties {
    id_sistema:            Rxswin;
    description_of_update: Rxswin;
}
