// Generated by https://quicktype.io

export interface AvisoActualizacion {
    id_documento:      string;
    id_fab_vehic:      string;
    systems_to_update: System[];
    date:              string;
}

export interface System {
    id_emb_sys:     string;
    description:    string;
    type_of_update: string;
}