// Generated by https://quicktype.io

export interface CertifEmbedSys {
    ref_doc_descripcion: string;
    id_homologador:      string;
    id_documento:        string;
    fecha:               string;
    firma:               string;
}