// Generated by https://quicktype.io

export interface DecisionTipoUpdate {
    id_doc:                       string;
    fecha:                        string;
    id_oem_manuf:                 string;
    update_type_decission:        string;
    quality_controls:             QualityControl[];
    changes_evaluation:           ChangesEvaluation[];
    regulation_impact_evaluation: RegulationImpactEvaluation[];
    modifications_on_system:      ModificationsOnSystem[];
    changes_in_functionality:     ChangesInFunctionality[];
}

export interface ChangesEvaluation {
    name_of_change: string;
    description:    string;
    observaciones:  string;
}

export interface ChangesInFunctionality {
    name_of_functionality: string;
    description:           string;
    change_applied:        string;
}

export interface ModificationsOnSystem {
    modification_name: string;
    description:       string;
}

export interface QualityControl {
    id_control:  string;
    description: string;
}

export interface RegulationImpactEvaluation {
    id_rule:     string;
    impact:      string;
    conclusions: string;
}