// Generated by https://quicktype.io

export interface DescripcionVehic {
    id_doc:       string;
    codif_modelo: CodifModelo;
    sistemas:     Sistema[];
}

export interface CodifModelo {
    marca:       string;
    modelo:      string;
    id_vehículo: string;
}

export interface Sistema {
    nombre:  string;
    manager: Manager;
}

export interface Manager {
    identificador:        string;
    nombre:               string;
    sistemas_controlados: string[];
}