// Generated by https://quicktype.io

export interface Justification {
    id_documento:       string;
    id_fab:             string;
    id_doc_descripcion: string;
    decission:          string;
    justification:      string;
    date:               string;
}