// Generated by https://quicktype.io

export interface Pruebas {
    id_prueba:         string;
    id_documento:      string;
    id_oem_manuf:      string;
    id_embbed_sys:     string;
    sistemas_probados: System[];
    tipo_de_prueba:    string;
    description:       string;
    expected_results:  string;
    obtained_results:  string;
    proof_validation:  string;
    date:              string;
}

export interface System {
    type: string;
}