// Generated by https://quicktype.io

export interface VersionInfo {
    id_documento:         string;
    version:              string;
    integrity_validation: string;
    RXSWIN:               string;
    updated_systems:      UpdatedSystem[];
}

export interface UpdatedSystem {
    id_sistema:            string;
    description_of_update: string;
}